version: "3.9"
services:
  online:
    image: "node:latest"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../:/home/node/app
    command:  bash -c "yarn && ./run-all.sh"
    depends_on:
      - redis

  redis:
    image: redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../:/myapp
      - ./generate-nginx-conf.sh:/docker-entrypoint.d/10-generate-nginx-conf.sh
    depends_on:
      - online
      - redis