version: "3.9"
services:
  online:
    image: "node:latest"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - "../:/home/node/app"
      - "${RUN_DIR:-../run}:/home/node/app/run"
    command:  bash -c "yarn && ./run-all.sh"
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "${RUN_DIR:-../run}/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - online
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"